# -*- coding: utf-8 -*-
"""customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13S03q0MLPxenmQgVF4REUe9ITjKeIxzd
"""

# ------------------ Data Cleaning Script for marketing_campaign.csv ------------------

import pandas as pd
import numpy as np

# 1. Load dataset (file must be uploaded to Colab working directory first)
file_path = "marketing_campaign.csv"   # <-- make sure this file is in your Colab folder
df = pd.read_csv(file_path, sep="\t")  # dataset is tab-separated

print("Original dataset shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

# 2. Identify and handle missing values
print("\nMissing values before cleaning:")
print(df.isnull().sum())

# Fill numeric columns with median, categorical with mode
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype in ['int64', 'float64']:
            df[col] = df[col].fillna(df[col].median())
        else:
            df[col] = df[col].fillna(df[col].mode()[0])

# 3. Remove duplicate rows
df = df.drop_duplicates()

# 4. Standardize text values (examples: education, marital_status)
df['Education'] = df['Education'].str.strip().str.title()
df['Marital_Status'] = df['Marital_Status'].str.strip().str.title()

# 5. Convert date formats to consistent type
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], errors='coerce', dayfirst=True)

# 6. Rename column headers (clean, lowercase, underscores)
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# 7. Check and fix data types
if df['year_birth'].dtype != 'int64':
    df['year_birth'] = df['year_birth'].astype(int)
if df['income'].dtype != 'float64':
    df['income'] = df['income'].astype(float)

print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\nDataset info after cleaning:")
print(df.info())

print("\nSample of cleaned data:")
print(df.head())

# 8. Save cleaned dataset
output_file = "marketing_campaign_cleaned.csv"
df.to_csv(output_file, index=False)
print(f"\nCleaned dataset saved as: {output_file}")

from google.colab import drive
drive.mount('/content/drive')
